### ISSUE TITLE
 Error running AuthU_UmbracoDbOAuthRefreshTokenStore migration

### ISSUE THREAD

**Issue by jezmaghuyop** [mattbrailsford/umbraco-authu#43]
Exception:
System.Data.SqlClient.SqlException (0x80131904): Column names in each table must be unique. Column name 'DeviceId' in table 'OAuthRefreshToken' is specified more than once.

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)

   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)

   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()

   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery()

   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass2_0.<ExecuteNonQueryWithRetry>b__0()

   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)

   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteNonQueryWithRetry(IDbCommand command, RetryPolicy cmdRetryPolicy, RetryPolicy conRetryPolicy)

   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteNonQueryWithRetry(IDbCommand command, RetryPolicy retryPolicy)

   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteNonQueryWithRetry(IDbCommand command)

   at Umbraco.Core.Persistence.Database.Execute(String sql, Object[] args)

   at Umbraco.Core.Persistence.Migrations.MigrationRunner.ExecuteMigrations(IMigrationContext context, Database database)

   at Umbraco.Core.Persistence.Migrations.MigrationRunner.Execute(Database database, DatabaseProviders databaseProvider, Boolean isUpgrade)

   at Umbraco.Core.Persistence.Migrations.MigrationRunner.Execute(Database database, Boolean isUpgrade)

   at Our.Umbraco.AuthU.Data.Migrations.MigrationsRunner.RunMigrations(String version, String productName)

ClientConnectionId:8a6f99ea-c3a4-4249-b985-2f32a21d9e75

Error Number:2705,State:4,Class:16

**Comment by LasseKofoed** [comment]
Running Umbraco 7.14 having the same issue  on version 1.0.3

Please advice 

` 2020-02-05 21:28:02,783 [P4784/D3/T133] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:28:02,785 [P4784/D3/T133] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2020-02-05 21:28:02,785 [P4784/D3/T133] INFO  Umbraco.Core.PluginManager - Resolving umbraco.cms.businesslogic.macro.IMacroEngine
 2020-02-05 21:28:02,827 [P4784/D3/T133] INFO  Umbraco.Core.PluginManager - Resolved umbraco.cms.businesslogic.macro.IMacroEngine (took 41ms)
 2020-02-05 21:32:20,091 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Terminating
 2020-02-05 21:32:20,093 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Waiting for tasks to complete
 2020-02-05 21:32:20,102 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Terminating
 2020-02-05 21:32:20,102 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Waiting for tasks to complete
 2020-02-05 21:32:20,110 [P4784/D3/T119] INFO  Umbraco.Core.MainDom - Stopping...
 2020-02-05 21:32:20,127 [P4784/D3/T133] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [InstructionProcessing] Tasks completed, terminated
 2020-02-05 21:32:20,128 [P4784/D3/T119] INFO  Umbraco.Web.ExamineStartup - Examine shutting down
 2020-02-05 21:32:20,131 [P4784/D3/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Tasks completed, terminated
 2020-02-05 21:32:20,148 [P4784/D3/T119] INFO  Umbraco.Web.ExamineStartup - Complete (took 20ms)
 2020-02-05 21:32:20,150 [P4784/D3/T119] INFO  Umbraco.Core.MainDom - Released MainDom.
 2020-02-05 21:32:20,151 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Terminating
 2020-02-05 21:32:20,151 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Waiting for tasks to complete
 2020-02-05 21:32:20,153 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [HealthCheckNotifier] Tasks completed, terminated
 2020-02-05 21:32:20,153 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Terminating
 2020-02-05 21:32:20,153 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Waiting for tasks to complete
 2020-02-05 21:32:20,154 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Terminating
 2020-02-05 21:32:20,154 [P4784/D3/T131] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Tasks completed, terminated
 2020-02-05 21:32:20,154 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Waiting for tasks to complete
 2020-02-05 21:32:20,158 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Terminating
 2020-02-05 21:32:20,160 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Waiting for tasks to complete
 2020-02-05 21:32:20,158 [P4784/D3/T5] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Tasks completed, terminated
 2020-02-05 21:32:20,161 [P4784/D3/T130] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Tasks completed, terminated
 2020-02-05 21:32:20,163 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Terminating
 2020-02-05 21:32:20,163 [P4784/D3/T119] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Waiting for tasks to complete
 2020-02-05 21:32:20,165 [P4784/D3/T114] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Tasks completed, terminated
 2020-02-05 21:32:49,162 [P12204/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.14.0 application starting on Z-SERVER
 2020-02-05 21:32:49,354 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2020-02-05 21:32:49,408 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 54ms)
 2020-02-05 21:32:49,583 [P12204/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2020-02-05 21:32:49,592 [P12204/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2020-02-05 21:32:49,604 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:32:50,044 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 439ms)
 2020-02-05 21:32:50,045 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2020-02-05 21:32:50,048 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 3ms)
 2020-02-05 21:32:50,143 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:32:50,145 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2020-02-05 21:32:50,145 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2020-02-05 21:32:50,146 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2020-02-05 21:32:50,147 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:32:50,147 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2020-02-05 21:32:50,147 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2020-02-05 21:32:50,151 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 4ms)
 2020-02-05 21:32:50,200 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:32:50,200 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2020-02-05 21:32:50,201 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2020-02-05 21:32:50,201 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 1ms)
 2020-02-05 21:32:50,203 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:32:50,203 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2020-02-05 21:32:50,204 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2020-02-05 21:32:50,206 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 2ms)
 2020-02-05 21:32:57,833 [P12204/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2020-02-05 21:32:58,491 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2020-02-05 21:32:58,495 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 4ms)
 2020-02-05 21:32:58,768 [P12204/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2020-02-05 21:32:58,896 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:32:58,897 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2020-02-05 21:32:58,897 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2020-02-05 21:32:58,899 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 1ms)
 2020-02-05 21:32:59,420 [P12204/D2/T1] INFO  Umbraco.Core.Persistence.Migrations.MigrationRunner - Initializing database migrations
 2020-02-05 21:32:59,423 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:32:59,424 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2020-02-05 21:32:59,425 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Persistence.Migrations.IMigration
 2020-02-05 21:32:59,430 [P12204/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Persistence.Migrations.IMigration (took 4ms)
 2020-02-05 21:32:59,648 [P12204/D2/T1] INFO  Umbraco.Core.Persistence.Database - Create Table sql -1:
 CREATE TABLE [OAuthRefreshToken] ([Id] INTEGER NOT NULL IDENTITY(1,1),
[Key] NVARCHAR(255) NOT NULL,
[Subject] NVARCHAR(255) NOT NULL,
[UserType] NVARCHAR(255) NOT NULL,
[Realm] NVARCHAR(255) NOT NULL,
[ClientId] NVARCHAR(255) NOT NULL,
[DeviceId] NVARCHAR(255) NULL,
[IssuedUtc] DATETIME NOT NULL,
[ExpiresUtc] DATETIME NOT NULL,
[ProtectedTicket] NTEXT NOT NULL)
 2020-02-05 21:32:59,663 [P12204/D2/T1] INFO  Umbraco.Core.Persistence.Database - Primary Key sql -1:
 ALTER TABLE [OAuthRefreshToken] ADD CONSTRAINT [PK_OAuthRefreshToken] PRIMARY KEY CLUSTERED ([Id])
 2020-02-05 21:32:59,670 [P12204/D2/T1] INFO  Umbraco.Core.Persistence.Migrations.Initial.BaseDataCreation - Creating data in table OAuthRefreshToken
 2020-02-05 21:32:59,671 [P12204/D2/T1] INFO  Umbraco.Core.Persistence.Migrations.Initial.BaseDataCreation - Done creating data in table OAuthRefreshToken
 2020-02-05 21:32:59,676 [P12204/D2/T1] INFO  Umbraco.Core.Persistence.Database - New table 'OAuthRefreshToken' was created
 2020-02-05 21:32:59,677 [P12204/D2/T1] INFO  Umbraco.Core.Persistence.Migrations.MigrationRunner - Added UPGRADE migration 'CreateTable' to context
 2020-02-05 21:32:59,692 [P12204/D2/T1] INFO  Umbraco.Core.Persistence.Migrations.MigrationRunner - Added UPGRADE migration 'AddDeviceIdColumn' to context
 2020-02-05 21:32:59,733 [P12204/D2/T1] INFO  Umbraco.Core.Persistence.Migrations.MigrationRunner - Executing sql statement 1: ALTER TABLE [OAuthRefreshToken] ADD [DeviceId] NVARCHAR(255) NULL

 2020-02-05 21:32:59,751 [P12204/D2/T1] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Exception (500c342e).
System.Data.SqlClient.SqlException (0x80131904): Column names in each table must be unique. Column name 'DeviceId' in table 'OAuthRefreshToken' is specified more than once.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 279
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass2_0.<ExecuteNonQueryWithRetry>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.Database.Execute(String sql, Object[] args)
ClientConnectionId:bfb8690f-02ce-4906-8e5a-704c9bfb263d
Error Number:2705,State:4,Class:16
 2020-02-05 21:32:59,794 [P12204/D2/T1] ERROR Our.Umbraco.AuthU.Data.Migrations.MigrationsRunner - Error running AuthU_UmbracoDbOAuthRefreshTokenStore migration
System.Data.SqlClient.SqlException (0x80131904): Column names in each table must be unique. Column name 'DeviceId' in table 'OAuthRefreshToken' is specified more than once.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 279
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass2_0.<ExecuteNonQueryWithRetry>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.Database.Execute(String sql, Object[] args)
   at Umbraco.Core.Persistence.Migrations.MigrationRunner.ExecuteMigrations(IMigrationContext context, Database database)
   at Umbraco.Core.Persistence.Migrations.MigrationRunner.Execute(Database database, DatabaseProviders databaseProvider, Boolean isUpgrade)
   at Our.Umbraco.AuthU.Data.Migrations.MigrationsRunner.RunMigrations(String version, String productName) in C:\projects\umbraco-authu\src\Our.Umbraco.AuthU\Data\Migrations\MigrationsRunner.cs:line 25
ClientConnectionId:bfb8690f-02ce-4906-8e5a-704c9bfb263d
Error Number:2705,State:4,Class:16
 2020-02-05 21:32:59,998 [P12204/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2020-02-05 21:33:00,618 [P12204/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 4
 2020-02-05 21:33:00,704 [P12204/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 11877ms)
 2020-02-05 21:33:02,106 [P12204/D2/T12] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: https://xxxxx.xxx:443/umbraco
 2020-02-05 21:33:02,112 [P12204/D2/T12] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: https://xxxxxx.xxx:443/umbraco (UmbracoModule request)
 2020-02-05 21:33:07,654 [P12204/D2/T12] INFO  umbraco.content - Load Xml from file...
 2020-02-05 21:33:07,720 [P12204/D2/T12] INFO  umbraco.content - Loaded Xml from file.
 2020-02-05 21:33:10,270 [P12204/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:33:10,271 [P12204/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2020-02-05 21:33:10,271 [P12204/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2020-02-05 21:33:10,273 [P12204/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 1ms)
 2020-02-05 21:33:14,527 [P12204/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2020-02-05 21:33:14,527 [P12204/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2020-02-05 21:33:14,528 [P12204/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Deploy.IServiceConnector
 2020-02-05 21:33:14,529 [P12204/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Deploy.IServiceConnector (took 0ms)
 2020-02-05 21:34:07,863 [P12204/D2/T12] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2020-02-04 21.34.07
`

**Comment by mattbrailsford** [comment]
Not sure, but I have a feeling we might need a `.Do();` statement at the end of this line https://github.com/mattbrailsford/umbraco-authu/blob/master/src/Our.Umbraco.AuthU/Data/Migrations/AddDeviceIdColumnToOAuthRefreshTokenTable.cs#L16

Someone it welcome to try and see if that helps.
